services:
  - type: web
    name: swiggy-rag
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: RENDER
        value: "true"
      - key: PORT
        value: "10000"
    plan: free
